channels:
- conda-forge
dependencies:
- python=3.8.17
- pip<=20.3.3
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - numpy==1.23.4
  - psutil==5.9.5
  - scikit-learn==1.1.2
  - scipy==1.9.1
name: mlflow-env
