wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1694269883.530425
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.13.3
      8:
      - 5
